# 题目 1：数组创建练习

In [2]:
import numpy as np

## 使用`numpy`创建一个从 5 开始，到 50 结束（不包含 50），步长为 5 的一维数组

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

## 使用`numpy`创建一个从 0 到 1 之间均匀分布的 11 个元素的一维数组

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## 将上面两个数组转换为 3×3 的二维数组（提示：需要先截取合适长度）

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

# 题目 2：广播机制练习

## 创建一个 3×3 的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 使用`numpy`创建一个 3×3 的全零矩阵

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 使用`numpy`创建一个形状为 (3, 3) 的随机数组`A`（取值范围 0-10，整数）

array([[0, 0, 0],
       [0, 7, 4],
       [8, 2, 5]])

## 使用`numpy`创建一个形状为 (3, 1) 的数组`B`（元素为 1, 2, 3）

array([[1],
       [2],
       [3]])

## 计算`A + B`，观察广播效果

array([[ 1,  1,  1],
       [ 2,  9,  6],
       [11,  5,  8]])

array([[ 2,  2,  2],
       [ 2,  9,  6],
       [10,  4,  7]])

## 使用`numpy`创建一个形状为 (1, 3) 的数组`C`（元素为 4, 5, 6）

array([[4, 5, 6]])

## 计算`A * C`，观察广播效果

array([[ 0,  0,  0],
       [ 0, 35, 24],
       [32, 10, 30]])

## 尝试计算`B + C`，解释结果的形状为什么是 (3, 3)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

# 题目 3：索引切片练习

使用以下数组`arr`完成操作：

In [3]:
import numpy as np
np.random.seed(42)  # 设置随机种子，保证结果可复现
arr = np.random.randint(0, 100, size=(5, 5))  # 5×5的随机整数数组（0-99）
arr

array([[51, 92, 14, 71, 60],
       [20, 82, 86, 74, 74],
       [87, 99, 23,  2, 21],
       [52,  1, 87, 29, 37],
       [ 1, 63, 59, 20, 32]])

## 获取数组`arr`的第 2 行（索引从 0 开始）

array([20, 82, 86, 74, 74])

## 获取数组`arr`的第 3 列

array([14, 86, 23, 87, 59])

## 获取数组`arr`的前 3 行和前 3 列构成的子数组

array([[51, 92, 14],
       [20, 82, 86],
       [87, 99, 23]])

## 获取数组`arr`中所有大于 50 的元素

array([51, 92, 71, 60, 82, 86, 74, 74, 87, 99, 52, 87, 63, 59])

## 将数组`arr`中所有小于 30 的元素替换为 0

array([[51, 92,  0, 71, 60],
       [ 0, 82, 86, 74, 74],
       [87, 99,  0,  0,  0],
       [52,  0, 87,  0, 37],
       [ 0, 63, 59,  0, 32]])

## 获取数组`arr`中偶数行和奇数列的元素（即行索引 0,2,4；列索引 1,3）

array([[92, 71],
       [99,  0],
       [63,  0]])